name: tests & formatting
on: 
  push:
  pull_request:
    types: [opened]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check && cargo clippy --all-features -- -Dwarnings && cargo test --all-features
